.coveragerc
README.md
apprise_api/api/tests/test_get.py
apprise_api/api/tests/test_json_urls.py
apprise_api/api/urls.py
apprise_api/api/views.py

**Related issue (if applicable):** fixes #1 
The idea of this pull request is to add an additional API call to `/json/urls/{key}` which returns a JSON object identifying all of the URLs (and tags) loaded on the key identified.
- a 500 is returned on error
- a 204 (no data found) is returned if nothing is loaded for given key
- you must perform a **GET** to retrieve this information.
- a 200 response is returned when content is successfully returned.
The response might look like:
```json
{
"tags": ["devops", "admin", "me"],
"urls": [
{
"url": "slack://TokenA/TokenB/TokenC",
"tags": ["devops", "admin"]
},
{
"url": "discord://WebhookID/WebhookToken",
"tags": ["devops"]
},
{
"url": "mailto://user:pass@gmail.com",
"tags": ["me"]
}
]
}
```
In the event there is an error (a non-200 code …

support a /json/urls/{key} query to provide loaded details

---

apprise_api/api/templates/config.html

Tags associated with configurations are queried so that they can be looked up from the Notification Tab. It's just a slightly more user-friendly experience.
**Screenshot**:

Materialize Chips used in place of Notification Tags

---

apprise_api/api/tests/test_add.py
apprise_api/api/tests/test_json_urls.py
apprise_api/api/tests/test_notify.py
apprise_api/api/views.py

Thanks to the amazing efforts of @nedbat and [nedbat/coveragepy/issue/915](https://github.com/nedbat/coveragepy/issues/915); this wraps up `mock` references to `NamedTemporaryFile()`
- [Travis CI Ref](https://travis-ci.community/t/python-3-6-sqlite3-operationalerror-disk-i-o-error/6737)
- [Ned Batchelder's Blog - Call for Help - Bug 915](https://nedbatchelder.com/blog/202001/bug_915_please_help.html)
- [Hacker News Ref](https://news.ycombinator.com/item?id=22030974)
- [Ned Batchelder's Blog - Bug 915 Solved](https://nedbatchelder.com/blog/202001/bug_915_solved.html)

Testing reworked to handle NamedTemporaryFile() issue

---

apprise_api/api/templates/welcome.html

**Related issue (if applicable):** fixes #14 
Addresses issue on welcome page which provides examples that do not work with reference to `tag`

api reference to tags should have read tag

---

README.md
apprise_api/api/forms.py
apprise_api/api/templates/config.html
apprise_api/api/tests/test_add.py
apprise_api/api/tests/test_json_urls.py
apprise_api/api/tests/test_notify.py
apprise_api/api/views.py
requirements.txt

The following changes come bundled in this Pull Request (PR):
* Code clean up can be done with `AppriseConfig.add_config()` function and the new `ConfigMemory()` type  (_introduced in [PR apprise/199](https://github.com/caronc/apprise/pull/199)_) which eliminates the need to write the configuration to a file just so that it can be re-read.
* Configuration format can be auto-detected now (when deciding if it is `YAML` or `TEXT`)
**Note**: Test cases won't pass until [PR apprise/282](https://github.com/caronc/apprise/pull/282) makes it upstream into the official version.  The `requirements.txt` has already been updated to point to it.  For this reason this PR will remain open until Apprise catches up. Code has been tested to work great against the Apprise/Master branch though.

Drop unnecessary file I/O handling + Auto-Detect Configuration Format

---

etc/supervisord.conf

It's bad practice to run things as root. `nginx` handles changing its own users, but gunicorn doesn't, and so is always run as root.
This changes it to run as `www-data`, the same user nginx runs its child processes as.
It's worth noting this change will likely break existing installs, as apprise will no longer be able to write to the previously written configuration files.
(I've not done much in-depth testing on this change yet)

Don't run the web process as root

---

apprise_api/api/forms.py
apprise_api/api/tests/test_notify.py
apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/views.py

**Related issue (if applicable):** fixes n/a
This merge request just allows the default body format to be both configurable and preset to `TEXT` for a more consistent and expected notification flow.

Default body format handling added

---

README.md
apprise_api/core/settings/__init__.py

**Related issue (if applicable):** fixes n/a
Added console logging so you can actually see what is going on with each call to the underlining `apprise` service.

Added console logging with optional LOG_LEVEL env override

---

README.md
apprise_api/api/templates/config.html
apprise_api/api/tests/test_notify.py
apprise_api/api/views.py
apprise_api/core/settings/__init__.py
apprise_api/static/css/base.css
requirements.txt

**Related issue (if applicable):** fixes n/a
Allow the users of the api website to see more logging details after their notification has been issued.

Logging details available via Apprise/API/Website

---

apprise_api/api/forms.py
apprise_api/api/tests/test_stateful_notify.py

**Related issue (if applicable):** fixes #35 
It has been reported that if you remove a key and then recreate a new save to it, the content won't save.   This PR was created to attempt to add testing around this and reproduce it.
So far I have been unable to reproduce this, but the added test cases are still good to have.

Persistent Configuration Not Saving

---

README.md
apprise_api/api/templates/config.html

**Related issue (if applicable):** fixes #43 and #31 
Doc changes to the **README.md** are as follows:
> ### Config Directory Permissions
> Under the hood, An NginX services is reading/writing your configuration files as the user (and group) `www-data` which generally has the id of `33`.  In preparation so that you don't get the error: `An error occured saving configuration.` consider also setting up your local `/var/lib/apprise/config` permissions as:
> 
> ```bash
> # Create a user/group (if one doesn't already exist) owned
> # by the user and group id of 33
> id 33 &>/dev/null || sudo useradd \
>    --system --no-create-home --shell /bin/false \
>     -u 33 -g 33 www-data
> 
> # Securely set the directory limiting access to only those who
> # are part of the www-data group:
> sudo chmod …
```

Improved persistent configuration permission docs

---

README.md
apprise_api/api/context_processors.py
apprise_api/api/forms.py
apprise_api/api/templates/config.html
apprise_api/api/tests/test_add.py
apprise_api/api/tests/test_del.py
apprise_api/api/tests/test_json_urls.py
apprise_api/api/tests/test_stateful_notify.py
apprise_api/api/views.py
apprise_api/core/settings/__init__.py
apprise_api/static/css/base.css

**Related issue (if applicable):** fixes #45 and #46
A new global variable added called `APPRISE_CONFIG_LOCK` which defaults to **no**.  However, when initialized to **yes**, the Apprise API locks down all of configuration from being accessible (nor can it be modified).
**PROS:**
- Your private information you've added is inaccessible for prying eyes that you share the configuration with
- Your configuration can not be tampered with by anyone (including yourself)  If you need to modify your configuration, you will need to take the global lock off.
- Full notification support (both before and after the lock is engaged).  This specifically is useful for those who have pre-saved their persistent configuration as all of these can still be triggered. Non persistent notifications remain …

APPRISE_CONFIG_LOCK switch added for extra security

---

requirements.txt

Handle cryptography dependency issue since it now forces users to leverage Rust.
Since we aren't decrypting content (only encrypting for transmission), we aren't at risk for sticking to an earlier version for the time being.

force version of cryptography that doesn't require Rust

---

apprise_api/api/context_processors.py
apprise_api/api/templates/base.html
apprise_api/api/templates/config.html
apprise_api/core/settings/__init__.py
apprise_api/static/css/base.css

- Underlining version of Apprise now shows
- Some added help information on main page

Underlining Apprise version info added to Frontend Display

---

apprise_api/api/templates/config.html
apprise_api/static/css/base.css

Just some slight reformatting and re-wording of the help information found on the main configuration page when there is no configuration set yet.

slight re-wording on main configuration help screen

---

README.md
apprise_api/api/tests/test_notify.py
apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/views.py
apprise_api/core/settings/__init__.py
requirements.txt

In preparation for then new `apprise://` schema defined [here](https://github.com/caronc/apprise/wiki/Notify_apprise_api)  which allows users to use the Apprise CLI (or Python Development) to access and trigger additional notifications from an Apprise API server (this very service here). 
The preparation involves handling situations where someone has additionally defined the `apprise://` schema in this API Service. 
- :+1: **In a best case scenario**: one could load balance and have one API Server call another (and another) scaling the distribution of thousands of notifications.
- :-1: **In a worst case scenario**: one could configure the Apprise API server to cal itself (endlessly doing so) to cause a Denial of Service (DoS).
- **Note**: This is exactly what the `APPRISE_RECURSION_MAX` …

Server-side handling of new apprise:// schema

---

README.md
apprise_api/api/tests/test_notify.py
apprise_api/api/views.py

**Related issue (if applicable):** refs #103
At this time, all elements identified for `tag` entries on the notification are `or`'ed together which may not be the desired effect.
With this PR, you can post your notification with ` ` (space) to delimit `and`'d tags and `,` (comma) to delimit `or`'ed tags.
Ie:
|  value     | Effect|
| -------------------------------- | ------------------------------ |
| TagA                          |  TagA
| TagA, TagB                     |  TagA **OR** TagB
| TagA TagC, TagB       |  (TagA **AND** TagC) **OR** TagB
| TagB TagC              |  TagB **AND** TagC
If the space gets confusion, feel free to also use `+` (in liue of a space) and `|` (pipe) in lieu of a comma  (or a mix of) to help with your defining elements.  Whitespace around delimiters …

Added and/or support with tags

---

apprise_api/api/tests/test_notify.py
apprise_api/api/views.py

**Related issue (if applicable):** refs #109
A recent change to the regex handling to support comma's (`,`) and spaces (` `) to also act as `AND/OR` arguments broke the integration to the Apprise library for those using the CLI.
This restores the CLI and external `apprise://` references.

apprise:// payload handling fixed with tags from CLI

---

apprise_api/api/utils.py

Saving settings on Windows fails with:
```
Traceback (most recent call last):
File "C:\Users\Nathan\.pyenv\pyenv-win\versions\3.11.3\Lib\shutil.py", line 825, in move
os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Nathan\\.local\\apprise-api\\apprise_api\\var\\config\\27\\tmpi0utrc0z.tmp' -> 'C:\\Users\\Nathan\\.local\\apprise-api\\apprise_api\\var\\config\\27\\7a415748edb692e8bf8c4361e9777d92f2dfad2359bbd8c9fbcd49.text'
```
`mkstemp()` also returns an open file handle (that we don't use), which must be closed as Windows won't allow renaming an open file.

Fix failure to save settings on Windows

---

README.md
apprise_api/api/tests/test_notify.py
apprise_api/api/tests/test_stateful_notify.py
apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/views.py
apprise_api/var/plugin/README.md

**Related issue (if applicable):** refs #108
Support the loading of custom plugins.
```bash
docker run --name apprise \
-p 8000:8000 \
-v /var/lib/apprise/config:/config \
-v /var/lib/apprise/plugin:/plugin \
-d caronc/apprise:latest
```
You can set the `APPRISE_PLUGIN_PATHS` environment variable to over-ride the default path.
**Note:** This merge needs to hold off as while testing, i uncovered a bug with Apprise [fixed here](https://github.com/caronc/apprise/pull/853).

Custom plugin directory scanning support added

---

Dockerfile
README.md
requirements.txt

Just a small push that updates the documentation for users who want to pull/check out a different version of Apprise outside of the stable version which is always the default.

Updated documentation and README to help with controlling Apprise Ver

---

apprise_api/api/tests/test_stateful_notify.py
apprise_api/api/tests/test_stateless_notify.py
apprise_api/gunicorn.conf.py

**Related issue (if applicable):** refs #136 
Improved testing around the tag settings.

Improved test coverage and fixed broken tests

---

README.md
apprise_api/api/tests/test_add.py
apprise_api/api/tests/test_del.py
apprise_api/api/urls.py

Increased key length size from 64 characters to 128.  Also fixed a bug enforcing that keys specified are ignored if longer.

Increased key length maximum size to 128 characters

---

apprise_api/core/middleware/theme.py

The theme cookie has an invalid _expires_ date:
```
Set-Cookie:  theme=light; expires=time.struct_time(tm_year=2024, tm_mon=10, tm_mday=19, tm_hour=9, tm_min=22, tm_sec=51, tm_wday=5, tm_yday=293, tm_isdst=0); Path=/
```
With fix:
```
Set-Cookie:  theme=light; expires=Sat, 19 Oct 2024 09:22:58 GMT; Max-Age=31536000; Path=/
```

Fix expiry date in theme set-cookie

---

Dockerfile

**Related issue (if applicable):** None
Reduces the Docker image compressed size to about 10% of the original size.  In short, the cleanup was not actually doing anything, as it happens on a different image layer from where the files being removed were added.
The `builder` stage is now responsible for producing the wheel for `cryptography`.  It also installs the minimal profile from rustup, for a slight speed up as well.  No cleanup is necessary here, as it is discarded when done
The `runtime` installs only the necessary packages and consumes the built wheel.  `aptget` leftovers are properly cleaned up in the same layer.
Everything else related to the application itself remains unchanged and running the image locally seems to work, serving the dashboard and such.

Fix: Reduce Docker image size

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/tests.yml

**Related issue (if applicable):** None
This PR updates all the actions to the latest versions, dealing with any breaking changes (mostly that's just some syntax for docker/metadata-action).  This will remove all those pesky warnings about deprecated Node versions and usages of old style output setting.
To help keep them updated, a dependabot configuration file for monthly checks for action updates is added as well.
An example run is here: https://github.com/stumpylog/apprise-api/actions/runs/6869096389
[The failure](https://github.com/stumpylog/apprise-api/actions/runs/6869096389/job/18683013084#step:8:2355) is merely due to the attempt to push, the actual build is fine.

Updates all actions to latest versions

---

apprise_api/api/views.py

**Related issue (if applicable):** n/a
The primary reason for this was services like `ntfy` were showing up at the bottom of the list and not inline with the other services starting with `N`.  
The list is now sorted in a case insensitive manner for an improved presentation.

Services are now sorted in a case-insensitive manner

---

apprise_api/api/forms.py
apprise_api/api/tests/test_notify.py
apprise_api/api/views.py

When an attachment is provided, `body` should be optional. At least this is how the command-line works.

allow empty body when attachment is provided

---

README.md
apprise_api/api/tests/test_notify.py
apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/utils.py
requirements.txt

Support for Apprise v1.7.x

---

apprise_api/api/tests/test_stateful_notify.py

**Related issue (if applicable):** refs #146
This pull request so far just re-produces the problem with a test case. 
Issue directly relates to [here](https://github.com/caronc/apprise/pull/998) where the issue was resolved.  This PR can be pushed after Apprise is updated

Honor new Group Functionality introduced in Apprise v1.6.0

---

apprise_api/api/forms.py
apprise_api/api/tests/test_notify.py
apprise_api/api/views.py

**Related issue (if applicable):** refs #162 
- Added `tags` kw support
- Improved logging (addresses #158)

Support `tags` GET and POST arg in addition to `tag`

---

README.md
apprise_api/api/tests/test_attachment.py
apprise_api/api/tests/test_notify.py
apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/utils.py
apprise_api/api/views.py

Apprise API can now support providing URLs as attachments now; for example:
```bash
curl -X POST \
-F 'urls=mailto://user:pass@gmail.com' \
-F attachment=https://i.redd.it/my2t4d2fx0u31.jpg \
http://localhost:8000/notify
```
Here is the same example but using the keys:
```bash
curl -X POST \
-F attachment=https://i.redd.it/my2t4d2fx0u31.jpg \
http://localhost:8000/notify/apprise
curl -X POST \
-F attachment=https://hostname/path/to.one.attachment.jpg \
-F attachment=https://hostname:3000/path/to/another.pdf \
http://localhost:8000/notify/apprise
```
This PR also improves logging and drastically improves code coverage.

Attachments support URLs

---

apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/views.py

**Related issue (if applicable):** n/a
GET parameters `title`, `type`, and `format` can be passed on the URL to provide default values if nothing in the message body exists (this is already how Stateful Apprise POSTs are handled).  This is merely making both consistent.

Stateless GET Parameter Support

---

apprise_api/api/views.py

**Related issue (if applicable):** refs #171 
Better support references to `tags` (alias of `tag`) when specified.

bugfix to better support tags and/or tag

---

README.md
apprise_api/api/templates/config.html
apprise_api/api/templates/welcome.html
apprise_api/api/tests/test_notify.py
apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/views.py

**Related issue (if applicable):** refs #157
- Add `attach` as an alias of `attachment` to make the Apprise API a bit easier to use
- Improved Web API Documentation / Examples
- Updated `README.md` to also give examples

Support 'attach' keyword (alias of 'attachment')

---

apprise_api/api/tests/test_attachment.py
apprise_api/api/utils.py
apprise_api/api/views.py
apprise_api/core/settings/__init__.py

**Related issue (if applicable):** refs #176 
The `APPRISE_ATTACH_SIZE` global correctly handles attachment sizes again (defined in MB) and defaults to `200`.
Previous to this there was another variable (undocumented) fixing this value to 8MB.
This PR also makes server side logging a bit more explanatory as to why the attachment was not processed (should this be the case)

bugfix: APPRISE_ATTACH_SIZE correctly manages attachment size

---

apprise_api/api/forms.py
apprise_api/api/templates/base.html
apprise_api/api/templates/config.html
apprise_api/api/tests/test_notify.py
apprise_api/core/middleware/config.py

JavaScript error fix when config-lock env var set

---

README.md
apprise_api/api/payload_mapper.py
apprise_api/api/tests/test_payload_mapper.py
apprise_api/api/tests/test_stateful_notify.py
apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/views.py

**Related issue (if applicable):** refs #183
Added the ability to remap fields during a notification submission by using `:` (colon) in the GET args of the post.
For example, consider a situation where your server posts the following:
```json
{
"content": "Message body",
"subject": "Message title",
}
```
These fields can be mapped to what the Apprise API expects with the following URL:
```bash
curl -X POST   \
-F "body=Test Message" \
-F "tags=all"  \
"http://localhost:8000/notify/apprise-api-key?:content=body&:subject=title"
```
The above identifies `:content=body` which tells the Apprise API to map the `content` entry to `body`, and `:subject` tells it to map `subject` to `title`.    Effectively, your payload looks like this now which is exactly what Apprise needed! :rocket: :
```json
{ …
```

Added payload mapper

---

README.md
apprise_api/api/templates/config.html
apprise_api/api/tests/test_attachment.py
apprise_api/api/tests/test_healthecheck.py
apprise_api/api/tests/test_payload_mapper.py
apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/tests/test_webhook.py
apprise_api/api/urls.py
apprise_api/api/utils.py
apprise_api/api/views.py

**Related issue (if applicable):** refs #51 
Added health check endpoint `/status`
| Path         | Method | Description |
|------------- | ------ | ----------- |
| `/status/` |  GET  | Simply returns a server status.  The server http response code is a `200` if the server is working correcty and a `417` if there was an unexpected issue.  You can set the `Accept` header to `application/json` or `text/plain` for different response outputs.
Below is a sample of just a simple text response:
```bash
curl -X GET http://localhost:8000/status
```
Below is a sample of a JSON response:
```bash
curl -X GET -H "Accept: application/json" http://localhost:8000/status
```
The above output may look like this:
```json
{
"config_lock": false,
"status": {
"can_write_config": true,
"can_write_attach": true, …
```

Added healthcheck endpoint /status

---

Dockerfile
README.md
apprise_api/api/templates/base.html
apprise_api/api/templates/config.html
apprise_api/api/templates/welcome.html
apprise_api/api/tests/test_healthecheck.py
apprise_api/api/tests/test_notify.py
apprise_api/api/utils.py
apprise_api/api/views.py
apprise_api/core/context_processors.py
apprise_api/etc/nginx.conf
apprise_api/etc/supervisord.conf
apprise_api/static/css/base.css
apprise_api/static/css/theme-dark.min.css
apprise_api/supervisord-startup

**Related issue (if applicable):** refs #196
- Added `PUID` and `PGID` Environment variables to allow those to over-ride the default permissions.
- Built healthchecks into the website for better support to users.

Healthcheck web improvements + PUID & PGID support added to Docker

---

README.md

**Related issue (if applicable):** refs #212
Updated documentation

Kubernetes Deployment Configuration Example Added

---

.github/workflows/build.yml
Dockerfile

**Related issue (if applicable):** refs #217

Drop building cryptography from source

---

apprise_api/core/settings/__init__.py

**Related issue (if applicable):** refs #228
`LOG_LEVEL` previously only set the `apprise` handler to align with the environment variable set.  Updated to also set the `django` environment variable as well.

improved LOG_LEVEL environment variable handling

---

README.md
apprise_api/core/settings/__init__.py
apprise_api/core/urls.py
requirements.txt

https://github.com/caronc/apprise-api/issues/143

add basic prometheus metrics

---

README.md
apprise_api/etc/nginx.conf
apprise_api/gunicorn.conf.py
apprise_api/supervisord-startup

**Related issue (if applicable):** refs #211
Added 2 new environment variables that allow the exclusive enforcing of an IPv4 or IPv6 environment only.
* `IPV4_ONLY`: Eliminate any IPv6 configuration in place to run n an exclusive IPv4 mode
* `IPV6_ONLY`: Eliminate any IPv4 configuration in place to run in an exclusive IPv6 mode
For obvious reasons, it's ambigious to set both environment variables, so if this is detected, nothing is updated/changed within the docker environment.
E.g.:
```bash
docker run --name apprise 
-p 8000:8000 \
-e PUID=$(id -u) \
-e PGID=$(id -g) \
-e IPV4_ONLY=y \
-e APPRISE_STATEFUL_MODE=simple \
-e APPRISE_WORKER_COUNT=1 \
-d caronc/apprise:latest
```
In the example, i set the `IPV4_ONLY` to `y`, but really it doesn't matter what you equate the environment …

IPV4_ONLY and IPV6_ONLY environment control added

---

apprise_api/api/tests/test_attachment.py
apprise_api/api/utils.py

**Related issue (if applicable):** refs #168, [apprise/1200](https://github.com/caronc/apprise/discussions/1200), #169, 
Be a little less restrictive on the Attachment checking when they are disabled in the Apprise-API. This will signifigantly increase the user experience with those who choose to use [LSIO](https://www.linuxserver.io/) over my build as well since it has Apprise-API with attachments disabled by default.

Improved 'empty attachment handling' when feature is disabled

---

apprise_api/supervisord-startup

**Related issue (if applicable):** refs [discussion/229](https://github.com/caronc/apprise-api/discussions/229)
Removed `root` requirement to start the Apprise API Container

removed 'root' docker initialization requirement

---

.github/workflows/tests.yml
.gitignore
Dockerfile
Dockerfile.py312
apprise_api/supervisord-startup
docker-compose.yml
tox.ini

Upgraded to Python v3.12

---

apprise_api/api/tests/test_stateless_notify.py
apprise_api/api/views.py

This brings the Stateless /Notify API into parity with the Stateful API /Notify/{key} endpoint.
**Related issue (if applicable):** refs #252
* [NA] Tests added

Stateless Notify API now returns log data
