caronc/apprise-api

.travis.yml, tox.ini
Added Python 3.8 Testing to Travis CI
=> Added Python 3.8 to CI

apprise_api/api/tests/test_notify.py, apprise_api/api/tests/test_stateless_notify.py, apprise_api/api/views.py
**Related issue (if applicable):** refs #11
Returns a different 40X error code in the event 1 or more of the notifications could not be notified.  The error code chosen was 424 based on the [wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) lists.
=> HTTP 424 error code returned if one or more notifications fail

apprise_api/api/templates/welcome.html, apprise_api/gunicorn.conf.py
**Related issue (if applicable):** #16
=> Worker Timeout Increased

README.md, apprise_api/api/context_processors.py, apprise_api/api/templates/base.html, apprise_api/api/templates/config.html, apprise_api/api/templates/welcome.html, apprise_api/core/context_processors.py, apprise_api/core/settings/__init__.py
**Related issue (if applicable):** fixes n/a
=> BASE_URL environment variable added

.github/workflows/build.yml, Dockerfile
This fixes the multi-arch build pipeline but because of a bug in docker `buildx` with armv7 (https://github.com/docker/buildx/issues/395) support for that has been removed. Also because of the new requirements in the base package of apprise, armv6 is no longer supported too.
=> Fix build pipeline

.github/workflows/build.yml, Dockerfile
=> Workflow updated to handle cryptography dependency

apprise_api/api/templates/config.html
**Related issue (if applicable):** fixes #50 and  invalidates #48
Fixes URL reference
=> Fixed URL typo on main config html page

swagger.yaml
=> Add OpenAPI description

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, Dockerfile, tox.ini
Fixed it so builds work again on TravisCI
=> Fix Travis CI Build Process

apprise_api/api/forms.py, apprise_api/static/css/base.css
**Related issue (if applicable):** fixes #73
=> Monospace Font for Configuration Area

apprise_api/etc/nginx.conf
**Related issue (if applicable):** refs #71
Eliminate some flags on the internal Nginx configuration that are not required.
This will handle the SWAG issue brought up;  thank you @STaRDoGG for helping isolate the issue.
=> NginX config updated for better support with other external services

apprise_api/api/tests/test_notify.py, apprise_api/api/tests/test_stateless_notify.py, apprise_api/api/views.py
**Related issue (if applicable):** refs #89 
Updated code to correctly reflect changes made in Apprise v1.0.0
=> Updated SCHEMA MAP property to reflect changes in Apprise v1.0

README.md
Fixes a minor typo at the start of the README.md file.
Sorry I'm aware this is quite petty, but hopefully not a big deal!
=> Fixes incorrect work in README.md

README-es.md
translation of readme to spanish
=> translation of readme to spanish

requirements.txt
=> Add fcm plugin missing dependency

Dockerfile
=> Fixed Rust Build on latest Unbuntu (cryptography dep)

.coveragerc, .github/workflows/tests.yml, README.md, apprise_api/api/tests/test_notify.py, apprise_api/api/tests/test_stateful_notify.py, apprise_api/api/tests/test_stateless_notify.py, apprise_api/api/views.py, pytest.ini, setup.cfg
**Related issue (if applicable):** refs #106
Setting up GitHub Actions
=> Github Actions Test Cases

README.md, apprise_api/gunicorn.conf.py, requirements.txt
**Related issue (if applicable):** refs #117
Improvements made to Gunicorn's configuration in attempts to improve the resources consumed by the Apprise API when self hosted.
=> Improved on Gunicorn configuration for resource improvements

apprise_api/etc/nginx.conf
**Related issue (if applicable):** refs #127 
Update Nginx configuration so that it works with both ipv4 and ipv6
=> IPV6 NginX support

README.md
**Related issue (if applicable):** refs #158
Improved documentation describing different HTTP Return codes when using the Apprise API
=> Added API HTTP Return Code Documentation

apprise_api/api/templates/config.html, apprise_api/static/css/base.css, apprise_api/static/css/theme-dark.min.css, apprise_api/static/css/theme-light.min.css
**Related issue (if applicable):** refs #174 
Further improved tag selection on the Review tab
=> Improved tag selection on Review tab

README.md, apprise_api/api/templates/config.html, apprise_api/static/css/base.css, apprise_api/static/css/theme-dark.min.css, apprise_api/static/css/theme-light.min.css
Just improved tagging visuals so you can view the current tags that will be notified when preforming a test
=> Improved tagging visuals

Dockerfile, README.md, apprise_api/api/management/commands/storeprune.py, apprise_api/api/templates/config.html, apprise_api/api/tests/test_cli.py, apprise_api/api/tests/test_healthecheck.py, apprise_api/api/tests/test_stateless_notify.py, apprise_api/api/tests/test_utils.py, apprise_api/api/utils.py, apprise_api/api/views.py, apprise_api/core/settings/__init__.py, apprise_api/static/css/base.css, apprise_api/supervisord-startup, requirements.txt
**Related issue (if applicable):** refs #102 
Apprise v1.9.0 introduces Persistent Storage.  This is the adaptation of it into the web version.
=> Persistent Storage Support (Apprise v1.9.0+) Added

README.md
=> kubernetes deployment fix
